services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - symfony_network

  php:
    build: .
    volumes:
      - .:/var/www/html
    networks:
      - symfony_network
    depends_on:
      - database

networks:
  symfony_network:

volumes:
  postgres_data: